# needed to build LLVM
language: cpp
# GCC is too old to build LLVM
compiler: clang
sudo: false

# build libcxx and libcxxabi, needed to build LLVM
install:
  - pushd .
  - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
  - cd libcxx/lib && bash buildit && popd
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/libcxx/lib
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:$(pwd)/libcxx/include
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$(pwd)/libcxx/include
  - export LDFLAGS="$LDFLAGS -L$(pwd)/libcxx/lib"
  - pushd .
  - svn co --quiet http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi
  - cd libcxxabi/lib && bash buildit && popd
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/libcxxabi/lib
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:$(pwd)/libcxxabi/include
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$(pwd)/libcxxabi/include
  - export LDFLAGS="$LDFLAGS -L$(pwd)/libcxxabi/lib"

before_script:
  - mkdir -p build && cd build
  - ../configure --enable-optimize --disable-optimize-tests --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu --target=x86_64-unknown-linux-gnu
script:
  - make clean && make rustc-stage1

# Real testing happens on http://buildbot.rust-lang.org/
#
# See https://github.com/rust-lang/rust-buildbot
#     CONTRIBUTING.md#pull-requests

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - build
