[package]
authors = ["The Rust Project Developers"]
name = "rustc_lld"
version = "0.0.0"
build = "build.rs"

[lib]
name = "rustc_lld"
path = "lib.rs"
crate-type = ["dylib"]

[build-dependencies]
build_helper = { path = "../build_helper" }
gcc = "0.3.27"

[dependencies]
rustc_llvm = { path = "../librustc_llvm" }
