[package]
authors = ["The Rust Project Developers"]
build = "build.rs"
name = "compiler-rt"
version = "0.0.0"

[build-dependencies]
cmake = "0.1.10"
gcc = "0.3.17"

[lib]
name = "compiler_rt"
path = "lib.rs"
